services:
    keycloak-db:
        image: postgres:14
        container_name: keycloak-db
        env_file:
            -   ./.env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - keycloak_postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"

    keycloak:
        image: quay.io/keycloak/keycloak
        container_name: keycloak
        env_file:
            - ./.env
        environment:
            KC_DB: ${KC_DB}
            KC_DB_URL: ${KC_DB_URL}
            KC_DB_USERNAME: ${KC_DB_USERNAME}
            KC_DB_PASSWORD: ${KC_DB_PASSWORD}
            KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
            KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
        command: start-dev
        ports:
            - "8080:8080"
        depends_on:
            - keycloak-db

volumes:
    keycloak_postgres_data: